### PR TITLE
Redirect to HTTPS when APP_ENV=production, add HSTS

### LINKED ISSUE #28: Force HTTPS
Forcing HTTPS isn't working despite the attempt made in #14

### PR DESCRIPTION
**Pull request by supertassu**
closes #28

### CODE REVIEW

**Comment by stwalkerster** [comment]
Is HSTS not an option?

**Comment by supertassu** [comment]
> 
> 
> Is HSTS not an option?

Probably is, but that's not upon me to decide.

**Comment by dqwiki** [comment]
As I discussed with @supertassu it's not a bad idea to do both. Let's do that.

**Comment by supertassu** [comment]
> As I discussed with @supertassu it's not a bad idea to do both. Let's do that.

Done in 81a19d0f162ba2d8597a32efa4784bda8ea44655.

**Review by dqwiki — APPROVED** [review]

**Pull request merged**
