### PR TITLE
Add custom error messages on 401 /appeal/{id} and on 404 /public/appeal/view

### LINKED ISSUE #213: When logged out user visits private appeal view, display an userful error message instead of redirecting them to OAuth
Since the appealant might click a link to private appeal view, we should display a view with the appeal key input and a OAuth button instead of just redirecting them to OAuth.

### PR DESCRIPTION
**Pull request by supertassu**
closes #213

### CODE REVIEW

**Comment by dqwiki** [comment]
I generically approve of this. I'll look at the actual interface pages tomorrow and sign off then.

**Review by dqwiki — CHANGES_REQUESTED** [review]
One common complaint that I get is the amount of whitespace within the interface. I was going to modify the alerts I put in down to calmer things, but out of respect for your design, I will defer to you on how you want to handle the whitespace that h-tags add.

**Comment by supertassu** [comment]
I've made the headers `<h2>` which are smaller and have much less whitespace around them:
image
image

**Review by dqwiki — APPROVED** [review]
Love the look

**Pull request merged**
