### PR TITLE
Allow configuring permissions per-wiki

### LINKED ISSUE #140: Allow per-wiki customization of permissions required to read or respond to appeals
This is much easier once #106 is merged

### PR DESCRIPTION
**Pull request by supertassu**
closes #140

### CODE REVIEW

**Comment by dqwiki** [comment]
While i'm going over this, do 'steward', 'staff', 'developer' all have the default view, CU and OS permissions?

**Comment by supertassu** [comment]
> While i'm going over this, do 'steward', 'staff', 'developer' all have the default view, CU and OS permissions?

Developers have everything. 'steward' and 'staff' have the status quo which is equivalent to admin (that's hardcodes somewhere in Permission.php I believe)

**Comment by dqwiki** [comment]
Ok, Steward and staff should have CU OS, especially staff.

**Comment by supertassu** [comment]
{{done}}

**Review by dqwiki — APPROVED** [review]

**Pull request merged**
