### PR TITLE
Remove old appeal email #47

### LINKED ISSUE #47: Fix viewing of old appeals
Currently viewing old appeals results in a 500. I have a strong feeling it is caused by this as e-mail might be null:

https://github.com/UTRS2/utrs/blob/b2bf722ceb9057f305f3d8faa64e60b6680ec9a9/resources/views/appeals/oldappeal.blade.php#L22

### PR DESCRIPTION
**Pull request by dqwiki**
Should close #47

### CODE REVIEW

**Review by supertassu — COMMENTED** [review]
Technically speaking this is fine. I'm not sure about if every verified user should be able to access all details about old appeals (most concerned about field *Why do you think a block is affecting you?*, probably others), potentially that should be limited to sysops/admins? Not sure through.

**Comment by dqwiki** [comment]
Absolutely agree on that, thanks for pointing that out. Request review of changes.

**Comment by Scolet15** [comment]
I'm not a developer, but I would like to comment in this. I support removing old appeal e-mail, but I strongly oppose that only sysops and admins are able to access all details about old appeals. I think that only the field _Why do you think a block is affecting you?_ shall be private, however others shan't.

**Comment by dqwiki** [comment]
You need to provide a reasoning to oppose and not just oppose to oppose.

As I noted in the commit:
> //Enwiki is hardcoded here as all previous appeals were only on enwiki.
> //Since that had a different policy at the time, we have to still observe the same privacy level.

Also, I'm not sure you understand what we mean by old appeals. This only affects appeals before #30372 as they were done on the UTRS 1 system where - at the time - only admins had access to the appeals, and the privacy policy there reflected that. Therefore, I can't randomly change the policy unilaterally for those appeals.

Appeals in the new system will still be viewable based on the privacylevel/review column in the database.

**Comment by dqwiki** [comment]
@supertassu I'm going to go ahead and merge this. Had I known about the UTRS 1 appeals being still viewable, I would have already acted on this.

**Pull request merged**
